FONKSİYONUN ASIL AMACI PHP İLE FORM UZERİNDEKİ YADA GET UZERİNDEKİ DATA DEĞERLERİNİ SQL İNJECTİON SORGULARINDAN TEMİZLEYEREK TAMAMEN TEMİZ DATAYI VERİTABANINA GÖNDERMEK AMACI İLE YAZILMIŞTIR 

İYİ KULLANIMLAR.
